### ISSUE TITLE
Error - EmuConfig - Invalid SteamID

### ISSUE THREAD

**Issue by FractumSeraph** [SteamAutoCracks/Steam-auto-crack#53]
No matter what I put in the ID field, I get this error message.  
This program was working before without any issues, and I don't recall changing anything on my PC.  I'm not sure how to troubleshoot this.

> [DBG] [SteamAutoCrack.MainWindow] Checking all goldberg emulator file exists or not...
> [DBG] [SteamAutoCrack.Core.Utils.SteamAppList] Initializing Steam App list...
> [INF] [SteamAutoCrack.Core.Utils.SteamAppList] Applist already updated to latest version.
> [DBG] [SteamAutoCrack.Core.Utils.SteamAppList] App Count: 200645
> [INF] [SteamAutoCrack.Core.Utils.SteamAppList] Initialized Steam App list.
> [DBG] [SteamAutoCrack.Core.Utils.SteamAppList] Waiting for Steam App list initialized...
> [INF] [SteamAutoCrack.Core.Utils.Processor] Starting process...
> [ERR] [SteamAutoCrack.Core.Utils.EMUConfig] Invaild SteamID.
> [ERR] [SteamAutoCrack.Core.Utils.Processor] Failed to process.
> System.Exception: Invaild SteamID.
>    at SteamAutoCrack.Core.Utils.EMUConfig.SetSteamIDFromString(String str)
>    at SteamAutoCrack.Core.Config.EMUConfigs.GetEMUConfig()
>    at SteamAutoCrack.Core.Utils.Processor.ProcessFileGUI()

**Comment by FractumSeraph** [comment]
Pebkac issue. Spent almost an hour on these before I realized I had a checkbox checked that I didn't mean to.
